version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  automerged_updates:
    - match:
      dependency_type: "all"
      update_type: "semver:minor"
    - match:
      dependency_type: "all"
      update_type: "semver:patch"
